CXBOX-872 Fix test results

diff --git a/.github/workflows/build_qa_pr_or_main.yml b/.github/workflows/build_qa_pr_or_main.yml
--- a/.github/workflows/build_qa_pr_or_main.yml
+++ b/.github/workflows/build_qa_pr_or_main.yml
@@ -113,18 +113,28 @@ jobs:
       - name: Post test summary to PR
         if: always()
         run: |
-          REPORT_URL="https://cx-box.github.io/cxbox-code-samples/pull_request/${{ github.run_number }}"
-
-          PASSED=$(jq '.statistic.passed' target/allure-results/widgets/summary.json)
-          BROKEN=$(jq '.statistic.broken' target/allure-results/widgets/summary.json)
-          FAILED=$(jq '.statistic.failed' target/allure-results/widgets/summary.json)
-          SKIPPED=$(jq '.statistic.skipped' target/allure-results/widgets/summary.json)
-          UNKNOWN=$(jq '.statistic.unknown' target/allure-results/widgets/summary.json)
-
+            REPORT_URL="https://cx-box.github.io/cxbox-code-samples/pull_request/${{ github.run_number }}"
+            SUMMARY_URL="$REPORT_URL/widgets/summary.json"
+            
+            # Проверяем, доступен ли файл
+            if curl --output /dev/null --silent --head --fail "$SUMMARY_URL"; then
+            echo "::notice::Fetching test results from $SUMMARY_URL"
+            
+            PASSED=$(curl -s "$SUMMARY_URL" | jq '.statistic.passed')
+            BROKEN=$(curl -s "$SUMMARY_URL" | jq '.statistic.broken')
+            FAILED=$(curl -s "$SUMMARY_URL" | jq '.statistic.failed')
+            SKIPPED=$(curl -s "$SUMMARY_URL" | jq '.statistic.skipped')
+            UNKNOWN=$(curl -s "$SUMMARY_URL" | jq '.statistic.unknown')
+          
           echo "### 📊 Test Report: [View Report]($REPORT_URL)" >> $GITHUB_STEP_SUMMARY
-          echo "| ✅ Passed | ⚠️ Broken | ❌ Failed | ⏭ Skipped | ❓ Unknown |" >> $GITHUB_STEP_SUMMARY
-          echo "|----------|---------|--------|---------|---------|" >> $GITHUB_STEP_SUMMARY
-          echo "| $PASSED  | $BROKEN | $FAILED | $SKIPPED | $UNKNOWN |" >> $GITHUB_STEP_SUMMARY
+            echo "| ✅ Passed | ⚠️ Broken | ❌ Failed | ⏭ Skipped | ❓ Unknown |" >> $GITHUB_STEP_SUMMARY
+            echo "|----------|---------|--------|---------|---------|" >> $GITHUB_STEP_SUMMARY
+            echo "| $PASSED  | $BROKEN | $FAILED | $SKIPPED | $UNKNOWN |" >> $GITHUB_STEP_SUMMARY
+            
+            else
+            echo "::error::Failed to fetch test summary from $SUMMARY_URL"
+            exit 1
+            fi
 
       - name: Generate and add report URL to Job Summary
         if: always()
